config/routes.rb
Geendashboard::Application.routes.draw do
  root 'projects#index'

  get 'auth/:provider/callback' => 'sessions#create'
  delete 'auth' => 'sessions#destroy', as: 'sign_out'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  resources :projects do
    resources :involvements
    resource :task_list
  end

  resources :roles

  resources :properties

  resources :wunderlist_accounts

  resources :users do
    member do
      post 'message' => 'users#message'
    end
  end

  resources :docs

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/access.rb
class Access < ActiveRecord::Base
  belongs_to :property
  belongs_to :user
end

app/models/doc.rb
class Doc < ActiveRecord::Base
  belongs_to :user
end

app/models/involvement.rb
class Involvement < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :role
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :involvements
  has_one :wunderlist_task_list
end

app/models/property.rb
class Property < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :involvements
  has_many :docs
  has_many :projects, through: :involvements
  has_many :roles, through: :involvements
  has_one :wunderlist_account

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['name']
      user.email = auth['info']['email']
    end
  end
end

app/models/wunderlist_account.rb
require 'wunderlist'

class WunderlistAccount < ActiveRecord::Base
  belongs_to :user

  def lists
    wunderlist.get '/me/lists'
  end

  def items(list_id)
    wunderlist.get('/me/tasks').select { |task| task['list_id'] == list_id }
  end

  private
    def wunderlist
      wunderlist = Wunderlist.new
      wunderlist.token = token
      wunderlist
    end
end

app/models/wunderlist_task_list.rb
class WunderlistTaskList < ActiveRecord::Base
  belongs_to :project
  belongs_to :wunderlist_account

  def tasks
    JSON.parse(read_attribute(:tasks)).select do |task|
      not task['parent_id']
    end.sort_by do |task|
      [false, true].index(!!task['completed_by_id']) * 9001 +
        task['position'].to_f
    end
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  def index
    @docs = Doc.all
  end

  def show
    @doc = Doc.find params[:id]
  end

  def edit
  end

  def new
    @doc = Doc.new
  end

  def create
    @doc = Doc.new doc_params
    @doc.user = current_user

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  private
  def doc_params
    params.require(:doc).permit :title, :body
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    if current_user
      @projects = current_user.projects
      @properties = Property.all
    end
  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    @project = Project.find params[:id]

    if @project.update project_params
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def new
    @project = Project.new

    if current_user.wunderlist_account
      @lists = current_user.wunderlist_account.lists.map do |list|
        list['title']
      end
    end
  end

  def create
    @project = Project.new project_params

    if @project.save
      role = Role.find_or_create_by name: 'owner'
      involvement = @project.involvements.create user: current_user, role: role
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.find params[:id]
    @project.destroy

    redirect_to root_path
  end

  private
    def project_params
      params.require(:project).permit :name, :goal, :visible, :active
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @roles = Role.all
    @role = Role.new
  end

  def create
    @role = Role.new role_params

    if @role.save
      redirect_to roles_path
    else
      render roles_path
    end
  end

  def update
    @role = Role.find params[:id]

    if @role.update role_params
      redirect_to roles_path
    else
      render roles_path
    end
  end

  def destroy
    @role = Role.find params[:id]
    @role.destroy

    redirect_to roles_path
  end

  private
    def role_params
      params.require(:role).permit :name, :can_write
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    puts auth.inspect
    user = User.find_by(provider: auth['provider'], uid: auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, notice: 'Signed in'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Signed out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
  end

  def message
    @user = User.find params[:id]

    UserMailer.personal_message({ to: @user, from: current_user }).deliver

    @message = 'Your message has been sent!'
    render 'show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url user, size = 32
    default_url = 'retro'
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=#{CGI.escape(default_url)}"
  end
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/involvements_helper.rb
module InvolvementsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def can_write project
    project.involvements.find_by(user: current_user).role.can_write
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/docs/_form.html.erb
<%= form_for @doc do |f| %>
  <% if @doc.errors.any? %>
    <section class="errors">
      <h1><%= pluralize @doc.errors.count, 'error' %></h1>
      <ul>
        <% @doc.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </section>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/docs/edit.html.erb
<h1>Docs#edit</h1>
<p>Find me in app/views/docs/edit.html.erb</p>

app/views/docs/index.html.erb
<h1>Docs</h1>

<% @docs.each do |doc| %>
  <a href="<%= url_for doc %>">
    <article class="doc">
      <h1><%= doc.title %></h1>
      <p><span class="avatar"><%= image_tag avatar_url doc.user %> <%= doc.updated_at %></p>
    </article>
  </a>
<% end %>

<p><%= link_to 'Create doc', new_doc_path %></p>

app/views/docs/new.html.erb
<h1>New doc</h1>

<%= render 'form' %>

<%= link_to 'Back', docs_path %>

app/views/docs/show.html.erb
<article class="doc">
  <h1><%= @doc.title %></h1>
  <p>
    <span class="avatar"><%= image_tag avatar_url @doc.user %>
    created <%= @doc.created_at %>
    updated <%= @doc.updated_at %>
  </p>

  <pre><%= @doc.body %></pre>
</article>

<p><%= link_to 'Back', docs_path %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <section class="errors">
      <h1><%= pluralize @project.errors.count, 'error' %></h1>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </section>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name, list: 'wunderlist_lists' %>
    <datalist id="wunderlist_lists">
      <% @lists && @lists.each do |list| %>
        <option value="<%= list %>">
      <% end %>
    </datalist>
  </p>

  <p>
    <%= f.label :goal %>
    <%= f.text_area :goal %>
  </p>

  <p>
    <%= f.check_box :visible %>
    <%= f.label :visible %>
  </p>

  <p>
    <%= f.check_box :active %>
    <%= f.label :active %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/projects/_item.html.erb
<article class="project">
  <header>
    <h1><%= item.name %></h1>
  </header>

  <ul class="involved">
    <% item.involvements.each do |involvement| %>
      <li>
        <li>
          <span class="user">
            <%= link_to user_url involvement.user do %>
              <span class="avatar"><%= image_tag avatar_url involvement.user %></span>
            <% end %>
            <span class="role"><%= involvement.role.name %></span>
          </span>
        </li>
      </li>
    <% end %>
  </ul>

  <div class="content">
    <% if item.goal %>
      <p><%= item.goal %></p>
    <% end %>
  </div>

  <section class="tasks">
    <% if item.wunderlist_task_list %>
      <h1>Tasks</h1>

      <ul>
        <% item.wunderlist_task_list.tasks.each do |task| %>
          <li <% if task['completed_by_id'] %>class="completed"<% end %>>
            <input type="checkbox" disabled <% if task['completed_by_id'] %>checked<% end %>>
            <%= task['title'] %>
          </li>
        <% end %>
      </ul>

      <% if can_write item %>
        <%= form_for item.wunderlist_task_list, url: project_task_list_path(item) do |f| %>
          <p>
          <%= hidden_field_tag :list_id, item.wunderlist_task_list.wunderlist_id %>
            <%= f.submit %>
          </p>
        <% end %>
      <% end %>
    <% end %>

    <% if can_write item %>
      <p>
        <%= link_to 'Attach new Wunderlist', project_task_list_path(item) %>
      </p>
    <% end %>
  </section>

  <% if can_write item %>
    <nav>
      <p>
        <%= link_to 'Edit', edit_project_path(item) %>
        <%= link_to 'Destroy', project_path(item), method: :delete,
                    data: { confirm: 'Are you sure?' } %>
      </p>
    </nav>
  <% end %>
</article>

app/views/projects/edit.html.erb
<%= render 'form' %>

<h2>Involvements</h2>
<ul>
  <% @project.involvements.each do |involvement| %>
    <li>
      <%= involvement.user.email %> (<%= involvement.role.name %>)
      <%= link_to 'Delete', [@project, involvement], method: :delete,
                  data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>
<%= form_for [@project, @project.involvements.build] do |f| %>
  <fieldset>
    <legend>New involvement</legend>
    <p>
      <%= f.label :user_id %>
      <%= f.collection_select :user_id, User.all, :id, :name %>
    </p>
    <p>
      <%= f.label :role_id %>
      <%= f.collection_select :role_id, Role.all, :id, :name %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  </fieldset>
<% end %>

app/views/projects/index.html.erb
<%= render partial: 'item', collection: @projects %>

<section id="properties">
  <%= render partial: 'properties/item', collection: @properties %>
</section>

<% if current_user %>
  <nav>
    <p><%= link_to 'New project', new_project_path %></p>
    <p><%= link_to 'New property', new_property_path %></p>
  </nav>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/roles/_form.html.erb
<%= form_for role, namespace: role.id do |f| %>
  <% if @role.errors.any? %>
    <section class="errors">
      <h1><%= pluralize @role.errors.count, 'error' %></h1>
      <ul>
        <% @role.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </section>
  <% end %>

  <p>
    <%= f.text_field :name %>

    <%= f.check_box :can_write %>
    <%= f.label :can_write %>

    <%= f.submit %>

    <%= link_to 'Destroy', role_path(role), method: :delete,
                data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

app/views/roles/_item.html.erb
<article class="project">
  <header>
    <h1><%= link_to "Project: #{item.name}", item %></h1>
  </header>
  <div class="content">
    <% if item.goal %>
      <p><%= item.goal %></p>
    <% end %>
  </div>
  <nav>
    <p>
      <%= link_to 'Edit', edit_project_path(item) %>
      <%= link_to 'Destroy', project_path(item), method: :delete,
                  data: { confirm: 'Are you sure?' } %>
    </p>
  </nav>
</article>

app/views/roles/index.html.erb
<h1>Roles</h1>

<ul>
  <% @roles.each do |role| %>
    <li>
      <%= render 'form', role: role %>
    </li>
  <% end %>
</ul>

<%= render 'form', role: @role %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p>
  <span class="avatar">
    <%= image_tag avatar_url(@user, 256) %>
  </span>
</p>

<% if @message %>
  <p><%= @message %></p>
<% end %>

<%= form_tag({ action: 'message' }, method: :post) do |f| %>
  <p>
    <%= label_tag :message %>
    <%= text_area_tag :message %>
  </p>
  <p>
    <%= submit_tag 'Send message' %>
  </p>
<% end %>