geendashboard/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

import projects.views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'geendashboard.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', projects.views.ProjectList.as_view(), name='project-list'),
    url(r'^project/(?P<slug>[-_\w]+)/$', projects.views.ProjectDetail.as_view(), name='project-detail'),
    url(r'^project/(?P<slug>[-_\w]+)/wunderlist$', 'wunderlist.views.attach', name='wunderlist-attach'),

    url(r'^account/log-in$', 'django.contrib.auth.views.login', name='login'),
    url(r'^account/log-out$', 'django.contrib.auth.views.logout', { 'next_page': '/' }, name='logout'),

    url(r'^account/services/wunderlist$', 'wunderlist.views.settings', name='wunderlist-settings'),

    url(r'^admin/', include(admin.site.urls)),
)

profiles/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db.models import *

class Project(Model):
  name = CharField(blank=True, max_length=70)
  goal = TextField(blank=True)

  start = DateTimeField(blank=True, null=True)
  due = DateTimeField(blank=True, null=True)
  end = DateTimeField(blank=True, null=True)

  visible = BooleanField(default=False)
  active = BooleanField(default=False)

  slug = SlugField()

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('project-detail', args=(self.slug,))

class Role(Model):
  name = CharField(max_length=20)

  can_read = BooleanField(default=True)
  can_write = BooleanField(default=True)

  def __str__(self):
    return self.name

class Involvement(Model):
  user = ForeignKey(User)
  project = ForeignKey(Project)
  role = ForeignKey(Role)

  def __str__(self):
    return '%s in %s as %s' % (self.user, self.project, self.role)

wunderlist/models.py
from django.contrib.auth.models import User
from django.db.models import *
import json
import requests

from projects.models import *

class Account(Model):
  user = ForeignKey(User, unique=True)
  email = EmailField()
  token = CharField(max_length=255)
  issued = DateTimeField(auto_now=True)

  def get(self, path):
    return requests.get(settings.WUNDERLIST_API + path, headers={
      'Authorization': 'Bearer ' + self.token
    }).json()

  def lists(self):
    return self.get('me/lists')

  def items(self, list_id):
    tasks = self.get('me/tasks')
    return [task for task in tasks if task['list_id'] == list_id]

  def __str__(self):
    return 'Wunderlist account for %s' % self.email

class TaskList(Model):
  project = OneToOneField(Project, unique=True)
  wunderlist_id = CharField(max_length=255)
  account = ForeignKey(Account)
  updated = DateTimeField(auto_now=True)

  tasks = TextField(blank=True, null=True)

  def __str__(self):
    return 'Task list for %s' % self.project

  def get_tasks(self):
    tasks = [task for task in json.loads(self.tasks) if not task['parent_id']]
    tasks.sort(key=lambda task: (not not task['completed_by_id'], float(task['position'])))
    return tasks

wunderlist/forms.py
from django.conf import settings
from django.forms import *
from django.utils.translation import ugettext as _
import requests

class LoginForm(Form):
  wunderlist_email = EmailField()
  wunderlist_password = CharField(widget=PasswordInput)

  def clean(self):
    cleaned_data = super(LoginForm, self).clean()

    result = requests.post(settings.WUNDERLIST_API + 'login', data={
      'email': cleaned_data['wunderlist_email'],
      'password': cleaned_data['wunderlist_password']
    }).json()

    if 'errors' in result:
      raise ValidationError(_('Wrong email or password'), code='fail_to_authenticate')
    else:
      cleaned_data['token'] = result['token']

    return cleaned_data

profiles/views.py
from django.shortcuts import render

# Create your views here.

projects/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import DetailView
from django.views.generic import ListView

from projects.models import Involvement, Project

class ProjectList(ListView):
  context_object_name = 'project'

  def get_queryset(self):
    return Project.objects.filter(involvement__user=self.request.user)

  @method_decorator(login_required)
  def dispatch(self, *args, **kwargs):
    return super(ProjectList, self).dispatch(*args, **kwargs)

class ProjectDetail(DetailView):
  context_object_name = 'project'

  def get_queryset(self):
    return Project.objects.filter(involvement__user=self.request.user)

  @method_decorator(login_required)
  def dispatch(self, *args, **kwargs):
    return super(ProjectDetail, self).dispatch(*args, **kwargs)

wunderlist/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
import json

from projects.models import *
from wunderlist.forms import *
from wunderlist.models import *

@login_required
def settings(request):
  try:
    account = Account.objects.get(user=request.user)
    if request.method == 'POST':
      account.delete()
      return redirect('wunderlist-settings')
    else:
      return render(request, 'wunderlist/settings.html', { 'account': account })
  except Account.DoesNotExist:
    if request.method == 'POST':
      form = LoginForm(request.POST)
      if form.is_valid():
        email = form.cleaned_data['wunderlist_email']
        Account(
            user=request.user,
            email=form.cleaned_data['wunderlist_email'],
            token=form.cleaned_data['token']
        ).save()
        return redirect('wunderlist-settings')
    else:
      form = LoginForm()
    return render(request, 'wunderlist/settings.html', { 'form': form })

@login_required
def attach(request, slug):
  project = get_object_or_404(Project, slug=slug, involvement__user=request.user)
  try:
    account = Account.objects.get(user=request.user)
  except Account.DoesNotExist:
    return render(request, 'wunderlist/no_account.html')
  if request.method == 'POST' and 'list' in request.POST:
    items = account.items(request.POST['list'])
    task_list, _ = TaskList.objects.get_or_create(
        project=project,
        account=account,
    )
    task_list.wunderlist_id = request.POST['list']
    task_list.tasks = json.dumps(items, indent=2)
    task_list.save()
    return redirect(project.get_absolute_url())
  else:
    lists = account.lists()
    return render(request, 'wunderlist/attach.html', {
      'project': project,
      'lists': lists
    })

projects/templates/profiles/user.html
{% load gravatar %}

<span class="user">
  <span class="avatar"><img src="{% gravatar_url user.email %}"></span>
  <span class="name">{{ user.first_name|default:user }}</span>
  {% if role %}
    <span class="role">({{ role }})</span>
  {% endif %}
</span>

projects/templates/projects/project_base.html
{% extends 'base.html' %}

{% block content %}
  <article class="project">
    <header>
      <h1><a href="{{ project.get_absolute_url }}">{{ project.name }}</a></h1>
    </header>
    <div class="content">
      {% block project_content %}{% endblock %}
    </div>
  </article>
{% endblock %}

projects/templates/projects/project_container.html
<article class="project">
  <header>
    <h1><a href="{{ project.get_absolute_url }}">{{ project.name }}</a></h1>
  </header>
  <div class="content">
    {% block project_content %}{% endblock %}
  </div>
</article>

projects/templates/projects/project_detail.html
{% extends 'base.html' %}

{% block content %}
  {% include 'projects/project_item.html' %}
{% endblock %}

projects/templates/projects/project_item.html
{% extends 'projects/project_container.html' %}

{% block project_content %}
  {% if project.involvement_set.all.count %}
    <ul class="involved">
      {% for involvement in project.involvement_set.all %}
        <li>
          {% include 'profiles/user.html' with user=involvement.user role=involvement.role %}
        </li>
      {% endfor %}
    </ul>
  {% endif %}

  {% if project.goal %}
    <p>{{ project.goal }}</p>
  {% endif %}

  {% if project.start %}
    <p>Start: {{ project.start }}</p>
  {% endif %}
  {% if project.end %}
    <p>End: {{ project.end }}</p>
  {% endif %}
  {% if project.due %}
    <p>Due: {{ project.due }}</p>
  {% endif %}

  <section class="tasks">
    <h1>Tasks</h1>
    {% if project.tasklist %}
      <ul>
        {% for task in project.tasklist.get_tasks %}
        <li {% if task.completed_by_id %}class="completed"{% endif %}>
            <input type="checkbox" disabled {% if task.completed_by_id %}checked{% endif %}>
            {{ task.title|urlizetrunc:30 }}
          </li>
        {% endfor %}
      </ul>
    {% endif %}

    <form action="{% url 'wunderlist-attach' slug=project.slug %}" method="POST">
      {% csrf_token %}
      <p>
        <a href="{% url 'wunderlist-attach' slug=project.slug %}">[+ Attach new Wunderlist]</a>
        {% if project.tasklist %}
          <input type="hidden" name="list" value="{{ project.tasklist.wunderlist_id }}">
          <button>Refresh current Wunderlist</button>
        {% endif %}
      </p>
    </form>
  </section>
{% endblock %}

projects/templates/projects/project_list.html
{% extends 'base.html' %}

{% block content %}
  {% for project in object_list %}
    {% include 'projects/project_item.html' %}
  {% endfor %}
{% endblock %}

projects/templates/wunderlist/attach.html
{% extends 'projects/project_base.html' %}

{% block project_content %}
  <form method="POST">
    {% csrf_token %}
    <p>
      <select name="list">
        {% for list in lists %}
          <option value="{{ list.id }}">{{ list.title }}</option>
        {% endfor %}
      </select>
      <button>Attach and share</button>
  </form>
{% endblock %}

projects/templates/wunderlist/no_account.html
{% extends 'base.html' %}

{% block content %}
  <p>You have no Wunderlist account. <a href="{% url 'wunderlist-settings' %}">Set one up.</a>
{% endblock %}

projects/templates/wunderlist/settings.html
{% extends 'base.html' %}

{% block content %}
  {% if form %}
    <form method="POST">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <p><button>Log in</button></p>
    </form>
  {% else %}
    <p>You are logged in to Wunderlist as <b>{{ account.email }}</b>.</p>
    <form method="POST">
      {% csrf_token %}
      <p><button>Log out</button></p>
    </form>
  {% endif %}
{% endblock %}